#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : jupyter-packaging
Version  : 0.7.11
Release  : 3
URL      : https://files.pythonhosted.org/packages/59/bb/da9b70cb72d634ae361211da5211f5ae0f3c7583aa258eac24bd179d9b1a/jupyter-packaging-0.7.11.tar.gz
Source0  : https://files.pythonhosted.org/packages/59/bb/da9b70cb72d634ae361211da5211f5ae0f3c7583aa258eac24bd179d9b1a/jupyter-packaging-0.7.11.tar.gz
Summary  : Jupyter Packaging Utilities
Group    : Development/Tools
License  : BSD-3-Clause
Requires: jupyter-packaging-license = %{version}-%{release}
Requires: jupyter-packaging-python = %{version}-%{release}
Requires: jupyter-packaging-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
This package contains utilities for making Python packages with
            and without accompanying JavaScript packages.

%package license
Summary: license components for the jupyter-packaging package.
Group: Default

%description license
license components for the jupyter-packaging package.


%package python
Summary: python components for the jupyter-packaging package.
Group: Default
Requires: jupyter-packaging-python3 = %{version}-%{release}

%description python
python components for the jupyter-packaging package.


%package python3
Summary: python3 components for the jupyter-packaging package.
Group: Default
Requires: python3-core
Provides: pypi(jupyter_packaging)
Requires: pypi(packaging)

%description python3
python3 components for the jupyter-packaging package.


%prep
%setup -q -n jupyter-packaging-0.7.11
cd %{_builddir}/jupyter-packaging-0.7.11

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1610131415
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/jupyter-packaging
cp %{_builddir}/jupyter-packaging-0.7.11/LICENSE %{buildroot}/usr/share/package-licenses/jupyter-packaging/7a88a926691422ae250d28e9a8214e9e40469383
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/jupyter-packaging/7a88a926691422ae250d28e9a8214e9e40469383

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
